# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nml-staff/parallel-step-44

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nml-staff/parallel-step-44

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nml-staff/parallel-step-44/CMakeFiles /home/nml-staff/parallel-step-44/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nml-staff/parallel-step-44/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named info

# Build rule for target.
info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 info
.PHONY : info

# fast build rule for target.
info/fast:
	$(MAKE) -f CMakeFiles/info.dir/build.make CMakeFiles/info.dir/build
.PHONY : info/fast

#=============================================================================
# Target rules for targets named strip_comments

# Build rule for target.
strip_comments: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 strip_comments
.PHONY : strip_comments

# fast build rule for target.
strip_comments/fast:
	$(MAKE) -f CMakeFiles/strip_comments.dir/build.make CMakeFiles/strip_comments.dir/build
.PHONY : strip_comments/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named parallel-step-44

# Build rule for target.
parallel-step-44: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 parallel-step-44
.PHONY : parallel-step-44

# fast build rule for target.
parallel-step-44/fast:
	$(MAKE) -f CMakeFiles/parallel-step-44.dir/build.make CMakeFiles/parallel-step-44.dir/build
.PHONY : parallel-step-44/fast

#=============================================================================
# Target rules for targets named release

# Build rule for target.
release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 release
.PHONY : release

# fast build rule for target.
release/fast:
	$(MAKE) -f CMakeFiles/release.dir/build.make CMakeFiles/release.dir/build
.PHONY : release/fast

#=============================================================================
# Target rules for targets named runclean

# Build rule for target.
runclean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 runclean
.PHONY : runclean

# fast build rule for target.
runclean/fast:
	$(MAKE) -f CMakeFiles/runclean.dir/build.make CMakeFiles/runclean.dir/build
.PHONY : runclean/fast

#=============================================================================
# Target rules for targets named debug

# Build rule for target.
debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 debug
.PHONY : debug

# fast build rule for target.
debug/fast:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/build
.PHONY : debug/fast

#=============================================================================
# Target rules for targets named distclean

# Build rule for target.
distclean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 distclean
.PHONY : distclean

# fast build rule for target.
distclean/fast:
	$(MAKE) -f CMakeFiles/distclean.dir/build.make CMakeFiles/distclean.dir/build
.PHONY : distclean/fast

parallel-step-44.o: parallel-step-44.cc.o

.PHONY : parallel-step-44.o

# target to build an object file
parallel-step-44.cc.o:
	$(MAKE) -f CMakeFiles/parallel-step-44.dir/build.make CMakeFiles/parallel-step-44.dir/parallel-step-44.cc.o
.PHONY : parallel-step-44.cc.o

parallel-step-44.i: parallel-step-44.cc.i

.PHONY : parallel-step-44.i

# target to preprocess a source file
parallel-step-44.cc.i:
	$(MAKE) -f CMakeFiles/parallel-step-44.dir/build.make CMakeFiles/parallel-step-44.dir/parallel-step-44.cc.i
.PHONY : parallel-step-44.cc.i

parallel-step-44.s: parallel-step-44.cc.s

.PHONY : parallel-step-44.s

# target to generate assembly for a file
parallel-step-44.cc.s:
	$(MAKE) -f CMakeFiles/parallel-step-44.dir/build.make CMakeFiles/parallel-step-44.dir/parallel-step-44.cc.s
.PHONY : parallel-step-44.cc.s

parameter-namespace.o: parameter-namespace.cc.o

.PHONY : parameter-namespace.o

# target to build an object file
parameter-namespace.cc.o:
	$(MAKE) -f CMakeFiles/parallel-step-44.dir/build.make CMakeFiles/parallel-step-44.dir/parameter-namespace.cc.o
.PHONY : parameter-namespace.cc.o

parameter-namespace.i: parameter-namespace.cc.i

.PHONY : parameter-namespace.i

# target to preprocess a source file
parameter-namespace.cc.i:
	$(MAKE) -f CMakeFiles/parallel-step-44.dir/build.make CMakeFiles/parallel-step-44.dir/parameter-namespace.cc.i
.PHONY : parameter-namespace.cc.i

parameter-namespace.s: parameter-namespace.cc.s

.PHONY : parameter-namespace.s

# target to generate assembly for a file
parameter-namespace.cc.s:
	$(MAKE) -f CMakeFiles/parallel-step-44.dir/build.make CMakeFiles/parallel-step-44.dir/parameter-namespace.cc.s
.PHONY : parameter-namespace.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... info"
	@echo "... strip_comments"
	@echo "... run"
	@echo "... rebuild_cache"
	@echo "... parallel-step-44"
	@echo "... release"
	@echo "... runclean"
	@echo "... debug"
	@echo "... distclean"
	@echo "... parallel-step-44.o"
	@echo "... parallel-step-44.i"
	@echo "... parallel-step-44.s"
	@echo "... parameter-namespace.o"
	@echo "... parameter-namespace.i"
	@echo "... parameter-namespace.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

